### ISSUE TITLE
Set up Zenodo archiving

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#144] opened 2017-07-13 17:00 UTC

**Comment by ethanwhite** [comment] 2017-07-13 18:57
I've linked the repo. Now all we need is a `0.1` release when the code is locked so that we can include the link in the manuscript.

**Comment by davharris** [comment] 2017-09-07 16:55
Closing this as a duplicate of #13, now that we have a Zenodo archive

**Closed by davharris** 2017-09-07 16:55 UTC
